### ISSUE TITLE
ConsoleUserInterface.constructUI test fails

### ISSUE THREAD

**Issue by yxyx-github** [yxyx-github/hwr-oop-group-4-todo#24]
This test is failing since the "Created main menu" commit.

**Comment by vreoio** [comment]
Will be fixed in next pull request.

**Comment by vreoio** [comment]
Will be fixed in next pull request

**Comment by yxyx-github** [comment]
Can you link the PR please?

**Comment by vreoio** [comment]
will do.

**Comment by termitehuegel** [comment]
fixed on dev
